// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package userlibconflictchecker.actions;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import userlibconflictchecker.proxies.WidgetsAnalyzeResult;

public class AnalyzeWidgets extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __WidgetsPath;
	private userlibconflictchecker.proxies.TargetWidgetsPath WidgetsPath;

	public AnalyzeWidgets(IContext context, IMendixObject WidgetsPath)
	{
		super(context);
		this.__WidgetsPath = WidgetsPath;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.WidgetsPath = this.__WidgetsPath == null ? null : userlibconflictchecker.proxies.TargetWidgetsPath.initialize(getContext(), __WidgetsPath);

		// BEGIN USER CODE
		this.doAnalyze();
		Core.commit(getContext(), results);
		return results;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AnalyzeWidgets";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode logger = Core.getLogger("AnalyzeWidgets");
	private final Map<String, ClientModuleInfo> clientModuleInfoMap = new HashMap<>();
	private final List<IMendixObject> results = new ArrayList<>();

	private void doAnalyze() throws Exception {

		String widgetsPath = this.WidgetsPath.getWidgetsPath();
		if (widgetsPath != null && widgetsPath.trim().length() > 0) {
			widgetsPath = widgetsPath.trim();
		} else {
			widgetsPath = Core.getConfiguration().getBasePath() + //
					Core.getConfiguration().getFileSeparator() + //
					".." + //
					Core.getConfiguration().getFileSeparator() + //
					"widgets";
			this.WidgetsPath.setWidgetsPath(widgetsPath);
		}
		File widgets = new File(widgetsPath);
		File[] widgetFileList = widgets.listFiles();

		if (widgetFileList == null || widgetFileList.length == 0) {
			logger.info("No userlib found in " + widgetsPath);
			return;
		}

		for (int i = 0; i < widgetFileList.length; i++) {
			File file = widgetFileList[i];
			if (file.isDirectory() || !file.exists() || !file.getName().endsWith(".mpk"))
				continue;
			traverseMpk(file.getName(), Files.newInputStream(file.toPath()), file.getName());
		}
	}

	private void traverseMpk(String mpkName, InputStream in, String path) throws Exception {
		try (ZipInputStream zis = new ZipInputStream(in)) {
			ZipEntry entry;

			while ((entry = zis.getNextEntry()) != null) {
				String current = path + "/" + entry.getName();
				if (entry.isDirectory()) {
					continue;
				}
				if (entry.getName().endsWith(".mpk")) {
					byte[] nestedZip = zis.readAllBytes();
					traverseMpk(
							mpkName + "/" + entry.getName(),
							new ByteArrayInputStream(nestedZip),
							current);
				} else {
					String name = entry.getName();
					if (name.equals("package.xml")) {
						byte[] data = zis.readAllBytes();
						DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
						factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
						//factory.setFeature("http://apache.org", true);
						DocumentBuilder builder = factory.newDocumentBuilder();
						Document document = builder.parse(new ByteArrayInputStream(data));
						Element packageElement = document.getDocumentElement();
						NodeList clientModuleList = packageElement.getElementsByTagName("clientModule");
						Element clientModule = (Element) clientModuleList.item(0);
						if (clientModule == null) {
							continue;
						}
						String clientModuleName = clientModule.getAttribute("name");
						String version = clientModule.getAttribute("version");
												clientModuleInfoMap.put(mpkName, new ClientModuleInfo(mpkName, clientModuleName, version, new java.util.Date(entry.getTime())));						
					} else if (name.endsWith(".xml")) {
						byte[] data = zis.readAllBytes();
						DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
						factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
						//factory.setFeature("http://apache.org", true);
						DocumentBuilder builder = factory.newDocumentBuilder();
						Document document = builder.parse(new ByteArrayInputStream(data));
						Element rootElement = document.getDocumentElement();
						String rootName = rootElement.getNodeName();
						if (rootName.equals("widget")) {
							NodeList nameList = rootElement.getElementsByTagName("name");
							String widgetName = nameList.getLength() > 0 ? nameList.item(0).getTextContent() : null;
							WidgetsAnalyzeResult moResult = new WidgetsAnalyzeResult(getContext());
							moResult.setMpkFileName(mpkName);
							moResult.setWidgetName(widgetName);
							moResult.setWidgetsAnalyzeResult_TargetWidgetsPath(WidgetsPath);
							results.add(moResult.getMendixObject());
						}
					}
				}
			}
			
			for (IMendixObject result : results) {
				WidgetsAnalyzeResult moResult = WidgetsAnalyzeResult.initialize(getContext(), result);
				ClientModuleInfo info = clientModuleInfoMap.get(moResult.getMpkFileName());
				if (info != null) {
					moResult.setVersion(info.version);
					moResult.setLastUpdated(info.lastUpdated);
				}
			}
		}
	}
	
	class ClientModuleInfo {
		String mpkFileName;
		String clientModuleName;
		String version;
		java.util.Date lastUpdated;

		public ClientModuleInfo(String mpkFileName, String clientModuleName, String version, java.util.Date lastUpdated) {
			this.mpkFileName = mpkFileName;
			this.clientModuleName = clientModuleName;
			this.version = version;
			this.lastUpdated = lastUpdated;
		}
	}
	// END EXTRA CODE
}
