// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package userlibconflictchecker.proxies;

public class WidgetsAnalyzeResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject widgetsAnalyzeResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserlibConflictChecker.WidgetsAnalyzeResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MpkFileName("MpkFileName"),
		WidgetName("WidgetName"),
		Version("Version"),
		LastUpdated("LastUpdated"),
		WidgetsAnalyzeResult_TargetWidgetsPath("UserlibConflictChecker.WidgetsAnalyzeResult_TargetWidgetsPath");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WidgetsAnalyzeResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WidgetsAnalyzeResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject widgetsAnalyzeResultMendixObject)
	{
		if (widgetsAnalyzeResultMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, widgetsAnalyzeResultMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.widgetsAnalyzeResultMendixObject = widgetsAnalyzeResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WidgetsAnalyzeResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static userlibconflictchecker.proxies.WidgetsAnalyzeResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return userlibconflictchecker.proxies.WidgetsAnalyzeResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static userlibconflictchecker.proxies.WidgetsAnalyzeResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new userlibconflictchecker.proxies.WidgetsAnalyzeResult(context, mendixObject);
	}

	public static userlibconflictchecker.proxies.WidgetsAnalyzeResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return userlibconflictchecker.proxies.WidgetsAnalyzeResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MpkFileName
	 */
	public final java.lang.String getMpkFileName()
	{
		return getMpkFileName(getContext());
	}

	/**
	 * @param context
	 * @return value of MpkFileName
	 */
	public final java.lang.String getMpkFileName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MpkFileName.toString());
	}

	/**
	 * Set value of MpkFileName
	 * @param mpkfilename
	 */
	public final void setMpkFileName(java.lang.String mpkfilename)
	{
		setMpkFileName(getContext(), mpkfilename);
	}

	/**
	 * Set value of MpkFileName
	 * @param context
	 * @param mpkfilename
	 */
	public final void setMpkFileName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mpkfilename)
	{
		getMendixObject().setValue(context, MemberNames.MpkFileName.toString(), mpkfilename);
	}

	/**
	 * @return value of WidgetName
	 */
	public final java.lang.String getWidgetName()
	{
		return getWidgetName(getContext());
	}

	/**
	 * @param context
	 * @return value of WidgetName
	 */
	public final java.lang.String getWidgetName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WidgetName.toString());
	}

	/**
	 * Set value of WidgetName
	 * @param widgetname
	 */
	public final void setWidgetName(java.lang.String widgetname)
	{
		setWidgetName(getContext(), widgetname);
	}

	/**
	 * Set value of WidgetName
	 * @param context
	 * @param widgetname
	 */
	public final void setWidgetName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String widgetname)
	{
		getMendixObject().setValue(context, MemberNames.WidgetName.toString(), widgetname);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @return value of LastUpdated
	 */
	public final java.util.Date getLastUpdated()
	{
		return getLastUpdated(getContext());
	}

	/**
	 * @param context
	 * @return value of LastUpdated
	 */
	public final java.util.Date getLastUpdated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastUpdated.toString());
	}

	/**
	 * Set value of LastUpdated
	 * @param lastupdated
	 */
	public final void setLastUpdated(java.util.Date lastupdated)
	{
		setLastUpdated(getContext(), lastupdated);
	}

	/**
	 * Set value of LastUpdated
	 * @param context
	 * @param lastupdated
	 */
	public final void setLastUpdated(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastupdated)
	{
		getMendixObject().setValue(context, MemberNames.LastUpdated.toString(), lastupdated);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WidgetsAnalyzeResult_TargetWidgetsPath
	 */
	public final userlibconflictchecker.proxies.TargetWidgetsPath getWidgetsAnalyzeResult_TargetWidgetsPath() throws com.mendix.core.CoreException
	{
		return getWidgetsAnalyzeResult_TargetWidgetsPath(getContext());
	}

	/**
	 * @param context
	 * @return value of WidgetsAnalyzeResult_TargetWidgetsPath
	 * @throws com.mendix.core.CoreException
	 */
	public final userlibconflictchecker.proxies.TargetWidgetsPath getWidgetsAnalyzeResult_TargetWidgetsPath(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		userlibconflictchecker.proxies.TargetWidgetsPath result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WidgetsAnalyzeResult_TargetWidgetsPath.toString());
		if (identifier != null) {
			result = userlibconflictchecker.proxies.TargetWidgetsPath.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WidgetsAnalyzeResult_TargetWidgetsPath
	 * @param widgetsanalyzeresult_targetwidgetspath
	 */
	public final void setWidgetsAnalyzeResult_TargetWidgetsPath(userlibconflictchecker.proxies.TargetWidgetsPath widgetsanalyzeresult_targetwidgetspath)
	{
		setWidgetsAnalyzeResult_TargetWidgetsPath(getContext(), widgetsanalyzeresult_targetwidgetspath);
	}

	/**
	 * Set value of WidgetsAnalyzeResult_TargetWidgetsPath
	 * @param context
	 * @param widgetsanalyzeresult_targetwidgetspath
	 */
	public final void setWidgetsAnalyzeResult_TargetWidgetsPath(com.mendix.systemwideinterfaces.core.IContext context, userlibconflictchecker.proxies.TargetWidgetsPath widgetsanalyzeresult_targetwidgetspath)
	{
		if (widgetsanalyzeresult_targetwidgetspath == null) {
			getMendixObject().setValue(context, MemberNames.WidgetsAnalyzeResult_TargetWidgetsPath.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WidgetsAnalyzeResult_TargetWidgetsPath.toString(), widgetsanalyzeresult_targetwidgetspath.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return widgetsAnalyzeResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final userlibconflictchecker.proxies.WidgetsAnalyzeResult that = (userlibconflictchecker.proxies.WidgetsAnalyzeResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
