// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package userlibconflictchecker.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the UserlibConflictChecker module
	public static void aCT_AnalyzeUserlib(IContext context, userlibconflictchecker.proxies.CustomUserlibPath _customUserlibPath)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CustomUserlibPath", _customUserlibPath == null ? null : _customUserlibPath.getMendixObject());
		Core.microflowCall("UserlibConflictChecker.ACT_AnalyzeUserlib").withParams(params).execute(context);
	}
	public static userlibconflictchecker.proxies.CustomUserlibPath dS_UserlibAnalyzePath(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("UserlibConflictChecker.DS_UserlibAnalyzePath").withParams(params).execute(context);
		return result == null ? null : userlibconflictchecker.proxies.CustomUserlibPath.initialize(context, result);
	}
}
